project:
  type: book

comments:
  hypothesis: true

book:
  title: Title
  author: Hailin Wang
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-polyu-thesis
  repo-actions: [edit, issue]
  search: true
  downloads: [pdf, docx]
  output-file: polyu-thesis
  navbar:
    search: true
  chapters:
    - index.md
    - chapters/chapter-1.md

# title: Title
# author: Author

abstract: |
  Abstract.

keywords:
  - Keyword 1
  - Keyword 1

subject: Subject
date: June 2025
version: Version

university: The Hong Kong Polytechnic University
department: Department of Civil and Environmental Engineering
institute: Thesis Research Centre

city: Hong Kong
address: Hung Hom, Kowloon

partner_university: Tongji University
partner_department: Department of Geotechnical Engineering

first_viewer: First viewer
second_viewer: Second viewer

supervisor: Supervisor
acknowledgements: Acknowledgements

bibliography: bibliography.bib

format:
  docx:
    output-file: polyu-thesis
  html:
    theme: cosmo
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
    output-file: polyu-thesis
  polyu-thesis-pdf:
    keep-tex: true
    output-file: polyu-thesis
