project:
  type: book

comments:
  hypothesis: true

book:
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-polyu-thesis
  repo-actions: [edit, issue]
  downloads: [pdf, docx]
  output-file: polyu-thesis
  sidebar:
    search: true

  title: Title
  author: Hailin WANG
  date: June 1, 2026
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - publications.qmd
    - chapters/01-introduction.qmd
    - chapters/02-chapter-2.qmd
    - references.qmd

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
    csl: apa.csl
  docx:
    output-file: polyu-thesis
    reference-doc: template.docx
    csl: apa.csl
  polyu-thesis-pdf:
    keep-tex: true
    fig-pos: "!htb"
    output-file: polyu-thesis
    include-in-header:
      - text: |
          \usepackage{enumitem}
          \setlist[description]{
            align=right,    % label alignment
            leftmargin=!,   % calculate left margin automatically
            labelwidth=2cm, % label width
            labelsep=0.5em, % space between label and description
            font=\bfseries\sffamily\color{thesisaccessory}, % label font
          }

    subject: Subject
    version: Version

    university: The Hong Kong Polytechnic University
    department: Department of Civil and Environmental Engineering
    institute: Thesis Research Centre

    city: Hong Kong
    address: Hung Hom, Kowloon

    partner_university: Tongji University
    partner_department: Department of Geotechnical Engineering

    first_viewer: First viewer
    second_viewer: Second viewer

    supervisor: Supervisor
