project:
  type: book

comments:
  hypothesis: true

book:
  title: Title
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-polyu-thesis
  repo-actions: [edit, issue]
  downloads: [pdf, docx]
  output-file: polyu-thesis
  sidebar:
    search: true
  chapters:
    - index.md
    - preamble.md
    - chapters/01-introduction.md
    - chapters/02-chapter-2.md

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
  docx:
    output-file: polyu-thesis
  polyu-thesis-pdf:
    keep-tex: true
    output-file: polyu-thesis

    author: Hailin Wang

    subject: Subject
    date: June 2025
    version: Version

    university: The Hong Kong Polytechnic University
    department: Department of Civil and Environmental Engineering
    institute: Thesis Research Centre

    city: Hong Kong
    address: Hung Hom, Kowloon

    partner_university: Tongji University
    partner_department: Department of Geotechnical Engineering

    first_viewer: First viewer
    second_viewer: Second viewer

    supervisor: Supervisor
