project:
  type: book

comments:
  hypothesis: true

book:
  title: Title
  author: Hailin Wang
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-polyu-thesis
  repo-actions: [edit, issue]
  search: true
  downloads: [pdf, docx]
  navbar:
    search: true
  chapters:
    - chapters/introduction.md

title: Title
author: Author

abstract: |
  This document is a template demonstrating the geotechnique format.

keywords:
  - Keyword 1
  - Keyword 1

subject: Subject
date: June 2025
version: Version

university: The Hong Kong Polytechnic University
department: Department of Civil and Environmental Engineering
institute: Thesis Research Centre

city: Hong Kong
address: Hung Hom, Kowloon

first_viewer: First viewer
second_viewer: Second viewer

supervisor: Supervisor
acknowledgement: Acknowledgement
declaration: Declaration

bibliography: bibliography.bib

format:
  docx: default
  html:
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
    output-file: index
  polyu-thesis-pdf: default
